//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slideshow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class slide
    {
        public int slide_id { get; set; }
        public string slide_name { get; set; }
        public string description_slide { get; set; }
        public string slide_clips { get; set; }
    }
}
